### PR TITLE
Add support for non-string compiler results

### PR DESCRIPTION
**Pull request by wooorm**
Note: there are reservations for this approach: https://github.com/unifiedjs/unified/issues/47#issuecomment-500255507.

Closes GH-47.

/cc @Rokt33r

### CODE REVIEW

**Comment by wooorm** [comment]
Failure in dtslint is due to: https://github.com/Microsoft/dtslint/blob/master/docs/no-unnecessary-generics.md

**Comment by wooorm** [comment]
I don’t have an informed enough opinion on this matter or TypeScript, so I’d abstain from voting for or against it: I created this PR based on a suggestion by @Rokt33r to continue the conversation.

I’m interested in hearing about the downsides from Junyoung.

@ChristianMurphy Is casting a solution we can apply here in unified, or does that happen on the user’s side?

**Comment by ChristianMurphy** [comment]
> Is casting a solution we can apply here in unified, or does that happen on the user’s side?

It would happen on the user's side, it's something we could document.

**Comment by wooorm** [comment]
That doesn’t sound too bad...

**Comment by wooorm** [comment]
@ChristianMurphy How should we document that? Here? https://github.com/unifiedjs/unified#returns-3

…maybe in also here? https://github.com/unifiedjs/unified#returns-6

…or should it go in *-react and the like other stringifier plugins?

**Comment by ChristianMurphy** [comment]
> or should it go in *-react and the other stringifier plugins?

This option sounds good to me.
The custom type will be custom per plugin.

**Comment by Rokt33r** [comment]
> or should it go in *-react and the other stringifier plugins?

Should be ideal.

Until it is released, we could notice users to do like `(processor.stringify(node, vfile) as unknown) as VNode`. as @ChristianMurphy suggested in https://github.com/unifiedjs/unified/issues/47#issuecomment-500255507 rather than merging this pr.

**Comment by Rokt33r** [comment]
@wooorm And I'm afraid that my decision is right because I'm not using remark with typescript now. My work is stale because I don't know which version of typescript should I support. https://github.com/remarkjs/remark/pull/383#issuecomment-500189439

If you give some kind of confirmation, I could start working again. In my opinion, we can ignore old versions of typescript until the type definitions for unified ecosystem are settled. [spectrum: TypeScript version(s) supported?
](https://spectrum.chat/unified/type-definitions/typescript-version-s-supported~7c1f6266-6be2-4d0a-b599-4ff93a6d0efd)

**Comment by wooorm** [comment]
Alright, I’ll close this PR.
We need a new PR closing GH-47 then, to add `(processor.stringify(node, vfile) as unknown) as VNode` to the docs here.

I’d appreciate if other people could do the same when needed to the other plugins returning non-strings.

> My work is stale because I don't know which version of typescript should I support. remarkjs/remark#383 (comment)

Sorry about that. I don’t have an informed opinion. Going with current (3?) seems good to me? Thanks for working on types!

**Comment by Rokt33r** [comment]
I guess we need higher than v3.1 at least. Then, I'll ignore lower version support until types are settled to unified ecosystem! I could start working again from this weekend!

**Comment by wooorm** [comment]
Awesome, sounds good to me!

**Pull request closed without merging**
