### PR TITLE
feature: support using unified as a template tag.

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Inspired by [hyperHTML](https://github.com/WebReflection/hyperhtml) and [lit-html](https://github.com/polymer/lit-html).
This PR adds new `templateTag` and `templateTagSync` functions.

These new functions allow unified to be applied as a tag/modifier function to any template string.

Simple Example:

```js
var unified = require('unified')
var markdown = require('remark-parse')
var remark2rehype = require('remark-rehype')
var doc = require('rehype-document')
var format = require('rehype-format')
var stringify = require('rehype-stringify')

var html = unified()
  .use(markdown)
  .use(remark2rehype)
  .use(doc)
  .use(format)
  .use(stringify)
  .templateTagSync

console.log(html`# Hello world!`.toString())
```

Yields:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <h1>Hello world!</h1>
  </body>
</html>
```

Interpolation Example:

```js
var unified = require('unified')
var markdown = require('remark-parse')
var remark2rehype = require('remark-rehype')
var doc = require('rehype-document')
var format = require('rehype-format')
var stringify = require('rehype-stringify')

var html = unified()
  .use(markdown)
  .use(remark2rehype)
  .use(doc)
  .use(format)
  .use(stringify)
  .templateTagSync

var file = html`
# Hello world!
${['First', 'Second', 'Third'].map(header => `## ${header} subsection`).join('\n')}
`

console.log(file.toString())
```

Yields:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <h1>Hello world!</h1>
    <h2>First subsection</h2>
    <h2>Second subsection</h2>
    <h2>Third subsection</h2>
  </body>
</html>
```

### CODE REVIEW

**Comment by wooorm** [comment]
Wow, this is super interesting!

I’m mainly wondering though, why do this? As in, your first example could be rewritten like so:

```js
var unified = require('unified')
var markdown = require('remark-parse')
var remark2rehype = require('remark-rehype')
var doc = require('rehype-document')
var format = require('rehype-format')
var html = require('rehype-stringify')

var html = unified()
  .use(markdown)
  .use(remark2rehype)
  .use(doc)
  .use(format)
  .use(html)
  .processSync

console.log(html(`# Hello world!`).toString())
```

Note the `processSync` and the parens. As they’re so similar, what’s the benefit of having this?

**Comment by ChristianMurphy** [comment]
As it stands it's mostly syntax sugar to avoid needing `()`. :slightly_smiling_face: 

Where it could go is more interesting, similar to how MDX allows adding non-markdown content mid-document, supporting template literals opens up the possibility of being able to mixin new content types into documents without needing a transpiler.

**Comment by wooorm** [comment]
@ChristianMurphy Right! So it gets interesting when it would be possible to “evaluate” the tag and the template in a build step?

**Comment by ChristianMurphy** [comment]
My thought would be to use data type to determine how to evaluate.
`typeof string` would evaluate using current parser.
`typeof object | function`, would switch to a different processing track.

**Comment by ChristianMurphy** [comment]
> `typeof object | function` would switch to a different processing track

In the alternative track, unified would parse the content surrounding the interpolated value, then add the interpolated value in as a second pass, directly into the AST.

E.G.

```js
const h = require('hastscript');

md2ht`## ${h('samp', 'sample header')}`
```

should generate

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <h2>
      <samp>
        sample header
      </samp>
    </h2>
  </body>
</html>

**Comment by wooorm** [comment]
@ChristianMurphy Huhh, very interesting indeed! I like where this is heading. But I foresee that a) this feature would change in the future, as b) we’re not entirely sure how this would work yet.

It could of course be that first we need the implementation before we can create interesting cases, but I feel like it’s better to develop both together. Develop both the implementation and the use-cases together?

**Comment by ChristianMurphy** [comment]
> I feel like it’s better to develop both together. Develop both the implementation and the use-cases together?

I agree.
Personally, I see this as the first step toward being able try out potential use cases.
If it should start as an external wrapper for unified, rather than a core processor function, that's fine.
This PR is mostly to get a discussion started.

**Comment by wooorm** [comment]
@hypercubed interested in hearing your thoughts on this!

**Comment by Hypercubed** [comment]
It's very interesting, and as you discussed, when you add the value interpolation.  In lit-html they have directives that can do may cool things like handling async functions.  At the moment I have couple of comments:

1) The unified transformations are text and static.  If the final result is text I don't really see directives being a help.  This is unlike lit-html where directives can do interesting things when rending the dom.  lit-html keep track of sstatic and dynamic parts of the template to allow effecient DOM updates.  Thsi simple has no benifit when generating static strings.

2) In lit-html the static and dynamic parts of the template are handeled very differenly.  The static parts must be complete html elements (for example html`<h1>${name}` + html`<h2>` doesn't work).  You cannot use dynamic content to generate elements (for example html`<${tag}>${name}<${tag}>`) for theis reason and also because the dynamic parts of HTML escaped.  The reason is in my point #1...  lit-html needs to seperate static and dynamic parts for effeicent updates.

3) In yoru example md2ht`## ${h('samp', 'sample header')}` you are mixing md and html... this can be an issue.  The function would need to know teh final product is html.

All this said I think it would be very intertsing in unified was able to convert to something like `lit-html`... then using a unified `md2lit` template method would be 💯

**Comment by ChristianMurphy** [comment]
Thanks for the feedback @wooorm and @Hypercubed!

> something like lit-html... then using a unified `md2lit` template method would be :100:

It would be.
For that, it'd be nice to have incremental parsing, allowing more targeted updates of content.

**Pull request closed without merging**
