### PR TITLE
ci: add GitHub actions continuous integration workflow

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Since unified is part of the actions beta, created a ci workflow, to try it out.
based off https://github.com/redotjs/redot/pull/17

:notebook: we already have Travis CI, so this would be a redundancy/backup.

### CODE REVIEW

**Comment by wooorm** [comment]
Thanks for working on this @ChristianMurphy!

My opinion is that two CIs doesn’t help much, but it also doesn’t hurt, and actions is in beta.
For now I’d say use both, maybe in the future we can switch to just GH?

**Comment by ChristianMurphy** [comment]
> For now I’d say use both, maybe in the future we can switch to just GH?

For now let's use both.

A longer term goal, when GH actions becomes stable, we could move to just actions.
It may also be interesting to see if adding the workflow to the [.github](https://github.com/unifiedjs/.github) repo could let us setup a default CI for unified projects.

**Comment by wooorm** [comment]
👍

Is default work flows already supported? We can also use github-tools or so to automatically add and manage files in repo's if not!

**Comment by ChristianMurphy** [comment]
> Is default work flows already supported?

Not sure, would need to try it out.

> We can also use github-tools or so to automatically add and manage files in repo's if not!

:+1:

**Pull request merged**
